#!/usr/bin/env python
# coding: utf-8

# In[12]:


class Car():
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading ='4'
    def get_descriptive_name(self):
        long_name = str(self.year)+' '+self.make +' '+self.model
        return long_name.title()
    def read_odometer(sefl):
        print('This car has ' + str(sefl.odometer_reading) + ' miles on it')
my_new_car = Car('audi','a4',2020)
print(my_new_car.get_descriptive_name())
my_new_car.read_odometer()


# In[6]:


class Car():
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        read_odometer(self)=0
    def get_descriptive_name(self):
        long_name = str(self.year)+' '+self.make +' '+self.model
        return long_name.title()
    def read_odometer(sefl):
        print('This car has ' + str(sefl.odometer_reading) + ' miles on it')
my_new_car = Car('audi','a4',2020)
print(my_new_car.get_descriptive_name())
my_new_car.read_odometer(0)


# el error que nos marco dice que no se puede asignar a la funcion llamada

# In[13]:


class Car():
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        self.car_tires='4'
        self.car_on='si'
    def get_descriptive_name(self):
        long_name = str(self.year)+' '+self.make +' '+self.model
        return long_name.title()
    def read_odometer(sefl):
        print('This car has ' + str(sefl.odometer_reading) + ' miles on it')
    def tires(self):
        print('El carro cuenta con '+str(self.car_tires)+' llantas')
    def power(self):
        print('¿El carro esta prendido?. '+str(self.car_on))
my_new_car = Car('audi','a4',2020)
print(my_new_car.get_descriptive_name())
my_new_car.read_odometer()
my_new_car.tires()
my_new_car.power()


# In[ ]:




