#!/usr/bin/env python
# coding: utf-8

# In[21]:


class Car():
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.odometer_reading = 0
        self.car_tires=0
        self.car_on=0
    def get_descriptive_name(self):
        long_name = str(self.year)+' '+self.make +' '+self.model
        return long_name.title()
    def read_odometer(self):
        print('This car has ' + str(self.odometer_reading) + ' miles on it')
    def update_odometer(self, mileage):
        self.odometer_reading =mileage
    def tires(self):
        print('El carro cuenta con '+str(self.car_tires)+' llantas')
    def update_tires(self, llantas):
        self.car_tires=llantas
    def power(self):
        print('¿El carro esta prendido?. '+str(self.car_on))
    def update_power(self, activated):
        self.car_on=activated
my_new_car = Car('audi','a4',2020)
print(my_new_car.get_descriptive_name())
my_new_car.update_odometer(54)
my_new_car.read_odometer()
my_new_car.update_tires(4)
my_new_car.tires()
my_new_car.update_power('si')
my_new_car.power()

