#!/usr/bin/env python
# coding: utf-8

# In[4]:


class Restaurant():
    def __init__(self, restaurant_name, cuisine_type):
        self.restaurant_name=restaurant_name
        self.cuisine_type=cuisine_type
        self.number_served=0
    def describe_restaurant(self):
        print('El restaurant "'+self.restaurant_name.title()+'" vende comida '+self.cuisine_type.title())
    def open_restaurant(self):
        print('El restaurant "'+self.restaurant_name.title()+'" esta abierto')
    def customers_served(self):
        print('Se han atendido a '+str(self.number_served)+' en total')
    def total_customers(self, customers):
        self.number_served=customers
print 'Nombre del restaurant:'
restaurant_name= raw_input()
print 'Tipo de comida'
cuisine_type= raw_input()
my_restaurant=Restaurant(restaurant_name, cuisine_type)
my_restaurant.describe_restaurant()
my_restaurant.open_restaurant()
my_restaurant.customers_served()


# In[5]:


class Restaurant():
    def __init__(self, restaurant_name, cuisine_type):
        self.restaurant_name=restaurant_name
        self.cuisine_type=cuisine_type
        self.number_served=0
    def describe_restaurant(self):
        print('El restaurant "'+self.restaurant_name.title()+'" vende comida '+self.cuisine_type.title())
    def open_restaurant(self):
        print('El restaurant "'+self.restaurant_name.title()+'" esta abierto')
    def customers_served(self):
        print('Se han atendido a '+str(self.number_served)+' en total')
    def total_customers(self, customers):
        self.number_served=customers
print 'Nombre del restaurant:'
restaurant_name= raw_input()
print 'Tipo de comida'
cuisine_type= raw_input()
my_restaurant=Restaurant(restaurant_name, cuisine_type)
my_restaurant.describe_restaurant()
my_restaurant.open_restaurant()
my_restaurant.total_customers(439)
my_restaurant.customers_served()





